name: vernal
channels:
  - pytorch
  - dglteam
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.10
  - biopython=1.77
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7
  - c-ares=1.16.1
  - ca-certificates=2020.7
  - cachetools=4.1
  - certifi=2020.6
  - cffi=1.14
  - chardet=3.0
  - click=7.1
  - cryptography=3.1
  - cycler=0.10
  - decorator=4.4
  - dgl=0.4
  - freetype=2.10
  - google-auth=1.21
  - google-auth-oauthlib=0.4
  - grpcio=1.30
  - idna=2.10
  - importlib-metadata=1.7
  - intel-openmp=2020.2
  - joblib=0.16
  - jpeg=9b
  - kiwisolver=1.2
  - lcms2=2.11
  - libcxx=10.0
  - libedit=3.1
  - libffi=3.3
  - libpng=1.6
  - libprotobuf=3.8
  - libtiff=4.1
  - llvm-openmp=10.0
  - lz4-c=1.9
  - markdown=3.2
  - matplotlib=3.3
  - matplotlib-base=3.3
  - mkl=2019.4
  - mkl-service=2.3
  - mkl_fft=1.1
  - mkl_random=1.1
  - ncurses=6.2
  - networkx=2.5
  - ninja=1.10
  - numpy=1.19
  - numpy-base=1.19
  - oauthlib=3.0
  - olefile=0.46
  - openssl=1.1
  - pandas=1.1
  - pillow=7.2
  - pip=20.2.2
  - protobuf=3.8
  - pyasn1=0.4
  - pyasn1-modules=0.2
  - pycparser=2.20
  - pyjwt=1.7
  - pyopenssl=19.1
  - pyparsing=2.4
  - pysocks=1.7
  - python=3.7
  - python-dateutil=2.8
  - python_abi=3.7
  - pytorch=1.4
  - pytz=2020.1
  - readline=8.0
  - requests=2.24
  - requests-oauthlib=1.3
  - rsa=4.6
  - scikit-learn=0.23
  - scipy=1.5
  - seaborn=0.10
  - setuptools=49.6
  - six=1.15
  - sqlite=3.33
  - tensorboard=2.3
  - tensorboard-plugin-wit=1.6
  - threadpoolctl=2.1
  - tk=8.6.
  - tornado=6.0
  - tqdm=4.48
  - urllib3=1.25
  - werkzeug=1.0
  - wheel=0.35
  - xz=5.2
  - zipp=3.1
  - zlib=1.2
  - zstd=1.4
  - pip:
    - multiset==2.1
    - libgfortran=3.0

